%% ?leri Kinematik


function [T01, T12, T23, T34, T04] = IleriKinematik(alfa,a,d,teta)



T01 = [             cos(radtodeg(teta(1))),             -sin(radtodeg(teta(1))),              0,               a(1);...
       sin(degtorad(teta(1)))*cos(degtorad(alfa(1))),cos(degtorad(teta(1)))*cos(degtorad(alfa(1))),-sin(degtorad(alfa(1))),-sin(degtorad(alfa(1)))*d(1);...
       sin(degtorad(teta(1)))*sin(degtorad(alfa(1))),cos(degtorad(teta(1)))*sin(degtorad(alfa(1))), cos(degtorad(alfa(1))), cos(degtorad(alfa(1)))*d(1);...
                                 0,                          0,             0,                  1 ] ;

T12 = [            cos(degtorad(teta(2))),             -sin(degtorad(teta(2))),             0,               a(2);...
       sin(degtorad(teta(2)))*cos(degtorad(alfa(2))),cos(degtorad(teta(2)))*cos(degtorad(alfa(2))),-sin(degtorad(alfa(2))),-sin(degtorad(alfa(2)))*d(2);...
       sin(degtorad(teta(2)))*sin(degtorad(alfa(2))),cos(degtorad(teta(2)))*sin(degtorad(alfa(2))), cos(degtorad(alfa(2))), cos(degtorad(alfa(2)))*d(2);...
                                 0,                          0,             0,                  1 ] ;
                             
T23 = [              cos(degtorad(teta(3))),             -sin(degtorad(teta(3))),             0,               a(3);...
       sin(degtorad(teta(3)))*cos(degtorad(alfa(3))),cos(degtorad(teta(3)))*cos(degtorad(alfa(3))),-sin(degtorad(alfa(3))),-sin(alfa(3))*d(3);...
       sin(degtorad(teta(3)))*sin(degtorad(alfa(3))),cos(degtorad(teta(3)))*sin(degtorad(alfa(3))), cos(degtorad(alfa(3))), cos(degtorad(alfa(3)))*d(3);...
                                 0,                          0,             0,                  1 ] ;
                             
T34 = [      cos(degtorad(teta(4))),           -sin(degtorad(teta(4))),             0,               a(4);...
       sin(degtorad(teta(4)))*cos(degtorad(alfa(4))),cos(degtorad(teta(4)))*cos(degtorad(alfa(4))),-sin(degtorad(alfa(4))),-sin(degtorad(alfa(4)))*d(4);...
       sin(degtorad(teta(4)))*sin(degtorad(alfa(4))),cos(degtorad(teta(4)))*sin(degtorad(alfa(4))), cos(degtorad(alfa(4))), cos(degtorad(alfa(4)))*d(4);...
                                 0,                          0,             0,                  1 ] ;
                             

T04 = T01*T12*T23*T34 ;


end